<?php
include_once "connection.php";
?>

<?php
$user=$_POST['user'];
$filename=md5($user).".lic";
$licenseinfo="DO NOT EDIT THIS file\r This license is issued to:".$user."\r: Valid-From:".time()."\r: Valid-Until:".strtotime('+1 year',time()).":\r copywirght adwaitanand".date('Y');
if($database->writefile($filename,$licenseinfo))
	echo "License File Generated";
	$datemodified=filemtime($filename);
if($database->insert($user,$filename,$datemodified))
	echo "<br>record successfully inserted.!!";


?>